//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rainfall_Live
    {
        public int ID { get; set; }
        public Nullable<int> Year_ref { get; set; }
        public Nullable<int> Rain_Full_Year { get; set; }
        public Nullable<int> Outflow_Full_Year { get; set; }
        public Nullable<int> Rain_Winter { get; set; }
        public Nullable<int> Outflow_Winter { get; set; }
        public Nullable<int> Rain_Summer { get; set; }
        public Nullable<int> Outflow_Summer { get; set; }
    }
}
